---

- hosts: web01
  gather_facts: false
  become: true

  tasks:
  - name: change listen port
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: "Listen 8080"
      regexp: "^Listen"
    notify: restart httpd

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted


