---

- hosts: webservers
  gather_facts: true
  become: true

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present

  - name: start httpd and enble it at boot
    service:
      name: httpd
      state: started
      enabled: true

  - name: copy wonderland.conf
    copy:
      src: wonderland.conf
      dest: /etc/httpd/conf.d/
      owner: root
      group: root
      mode: 0644
    notify: restart httpd

  - name: create /opt/httpd/wonderland directory
    file:
      path: /opt/httpd/wonderland
      state: directory
      owner: apache
      group: apache
      mode: 0750

  - name: create index.html
    blockinfile:
      path: /opt/httpd/wonderland/index.html
      state: present
      create: true
      block: |
        <h1>Hello from Wonderland!</h1>
        <p>Private IP is {{ ansible_default_ipv4.address }}</p> 
        <p>Last updated on {{ ansible_date_time.weekday }}, {{ ansible_date_time.date }}</p>
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      owner: apache
      group: apache
      mode: 0640


  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted

