---
# transform.yml

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    change_case: "This Is a STRING"
    list1: [ 0, 10, 3, 25 ]
    my_url: "http://user:password@www.acme.com:9000/dir/index.html?query=term#fragment"


  tasks:
  - name: change to upper case
    debug:
      msg: "{{ change_case | upper }}"
    tags: case

  - name: undefined variable
    debug:
      msg: "{{ undefined }}"
    ignore_errors: true
    tags: undef

  - name: undefined variable
    debug:
      msg: "{{ undefined | default('now_is_ok') }}"
    tags: undef

  - name: get maximum value from list
    debug:
      msg: "{{ list1 | max }}"
    tags: max

  - name: split url
    debug:
      msg: "{{ my_url | urlsplit }}"
    tags: split

  - name: split url
    debug:
      msg: "{{ my_url | urlsplit('hostname') }}"
    tags: split

  - name: split url
    debug:
      msg: "{{ my_url | urlsplit('scheme') }}"
    tags: split
